
services:
  postgres:
    image: postgres:12-bullseye
    environment:
        POSTGRES_DB: app_db
        POSTGRES_USER: app_user
        POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - "./local_db_init_scripts:/docker-entrypoint-initdb.d"
  # payment-stats-service local development
  app:
    build:
      context: .
      args:
        # install prod and dev requirements
        REQUIREMENTS: "requirements/*.txt"
    environment:
      DATABASE_DB: app_db
      DATABASE_USER: app_user
      DATABASE_PASSWORD: password
    depends_on:
      - postgres

    ports:
      - "6789:80"
