# [Choice] Python version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.10, 3.9, 3.8, 3.7, 3.6, 3-bullseye, 3.10-bullseye, 3.9-bullseye, 3.8-bullseye, 3.7-bullseye, 3.6-bullseye, 3-buster, 3.10-buster, 3.9-buster, 3.8-buster, 3.7-buster, 3.6-buster
ARG VARIANT=3.10-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/python:${VARIANT}

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH "${PYTHONPATH}/code"


# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
# ARG NODE_VERSION="none"
# RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends httpie \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# [Optional] If your requirements rarely change, uncomment this section to add them to the image.
RUN pip install --upgrade pip && pip install pip-tools
COPY requirements /tmp/pip-tmp/requirements
RUN pip-sync /tmp/pip-tmp/requirements/*.txt && rm -rf /tmp/pip-tmp

# install pre-commit in container - speeds up rebuilds
WORKDIR /tmp/pre-commit
COPY .pre-commit-config.yaml .
RUN git init . && pre-commit install-hooks
WORKDIR /
RUN rm -rf /tmp/pre-commit
